import { requireUser, getCurrentBusiness } from "@/lib/services/tenancy";
import { redirect } from "next/navigation";
import { OnboardingForm } from "./form";
import { SurgeLogo } from "@/components/brand/surge-logo";

export default async function OnboardingPage({
  searchParams,
}: {
  searchParams: Promise<{ add?: string }>;
}) {
  await requireUser();
  const sp = await searchParams;
  const isAdding = sp?.add === "1";

  const ctx = await getCurrentBusiness();
  // Only bounce to /app if they already have a business AND aren't deliberately
  // adding another one.
  if (ctx && !isAdding) redirect("/app");

  return (
    <div className="min-h-screen flex bg-background">
      {/* oaFloat/.oa-float went with the two blurred brand orbs it drove —
          nothing floats on this panel any more. oaRise stays: it is an
          opacity-and-translate entrance, which is motion, not colour. */}
      <style
        dangerouslySetInnerHTML={{
          __html:
            "@keyframes oaRise{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:none}}.oa-rise{animation:oaRise .7s cubic-bezier(0.16,1,0.3,1) both}",
        }}
      />

      {/* Brand panel — desktop only */}
      <div className="hidden lg:flex lg:w-1/2 relative overflow-hidden">
        {/* FLAT INK, where this was a 135deg sweep from oklch(0.21 0.045 265)
            to oklch(0.15 0.02 265). The value is the midpoint of the two stops
            it replaces, so the panel sits exactly where it used to read on
            average. It stays an inline OKLCH literal rather than becoming a
            token for the same reason the two stops were literals: this panel
            is ink in BOTH themes, so there is no theme-flipping token in
            globals.css that means it, and inventing one for a single element
            on a single route is a worse trade than the literal.
            White lettering on it: 18.83:1. The white/60 body copy: 7.18:1. */}
        <div className="absolute inset-0" style={{ background: "oklch(0.18 0.032 265)" }} />
        {/* THE TWO BLURRED BRAND ORBS ARE GONE. A disc under blur-3xl is a
            radial falloff rendered by the compositor — the same object as the
            dashboard's bloom, and it has the same flat form: none. Painting a
            hard-edged blue circle on the panel instead would be a worse thing
            than an empty panel. */}
        {/* The dot field STAYS and is not a colour gradient: the stop is at 1px
            with transparent at the same 1px, so every dot is one flat white at
            12% with nothing between it and the background. It is a texture
            generated by the gradient syntax, not a colour transition — the
            same class of thing as the film grain on the dashboard. */}
        <div
          className="absolute inset-0 opacity-[0.12]"
          style={{
            backgroundImage:
              "radial-gradient(oklch(1 0 0 / 0.5) 1px, transparent 1px)",
            backgroundSize: "28px 28px",
          }}
        />

        <div className="relative z-10 flex flex-col justify-between p-12 text-white w-full">
          {/* Horizontal lockup at the kit's 220px floor. Pinned dark: this
              panel is ink regardless of theme. Matches /login exactly — the
              two hero panels are the same surface. */}
          <div className="oa-rise">
            <SurgeLogo tone="dark" className="h-[65px] w-[220px]" />
          </div>

          <div className="max-w-md">
            <h2
              className="oa-rise text-3xl font-semibold tracking-tight leading-tight"
              style={{ animationDelay: "0.1s" }}
            >
              Run your whole operation from one place.
            </h2>
            <p
              className="oa-rise text-white/60 mt-4 text-sm leading-relaxed"
              style={{ animationDelay: "0.2s" }}
            >
              Payments, orders, customers, staff &mdash; Surge keeps the day-to-day
              moving so you can focus on the work.
            </p>
            <div
              className="oa-rise flex flex-wrap gap-2 mt-6"
              style={{ animationDelay: "0.3s" }}
            >
              {["Take payments", "Track orders", "Run multiple businesses"].map(
                (f) => (
                  <span
                    key={f}
                    className="text-xs px-3 py-1.5 rounded-full bg-white/10 ring-1 ring-white/20 text-white/80"
                  >
                    {f}
                  </span>
                )
              )}
            </div>
          </div>

          <div
            className="oa-rise text-xs text-white/40"
            style={{ animationDelay: "0.4s" }}
          >
            &copy; Surge &middot; surgetechpos.com
          </div>
        </div>
      </div>

      {/* Form panel */}
      <div className="flex-1 flex items-center justify-center p-6 sm:p-10">
        <OnboardingForm />
      </div>
    </div>
  );
}