import Link from "next/link";
import { notFound } from "next/navigation";
import { requireBusiness } from "@/lib/services/tenancy";
import { canAccess } from "@/lib/services/route-access";
import { hasFloorService } from "@/lib/modules/modes";
import { createClient } from "@/lib/supabase/server";
import { qrSvg } from "@/lib/qrcodegen";
import { PrintButton } from "./print-button";

export const dynamic = "force-dynamic";

// Print table QR codes: one scannable placard per table, encoding that table's
// pay-at-table / scan-to-order URL (/order/<businessId>/<elementId>). The QR is
// generated by a vendored, dependency-free encoder (lib/qrcodegen) — no external
// CDN. Read-only over floor_elements; no money-path coupling.
export default async function TableQrCodesPage() {
  const { business, role } = await requireBusiness();
  if (!hasFloorService(business) || !canAccess(role, "manage_settings")) {
    notFound();
  }

  const supabase = await createClient();
  const [{ data: plans }, { data: elements }] = await Promise.all([
    supabase.from("floor_plans").select("id, name, sort_order").eq("business_id", business.id),
    supabase
      .from("floor_elements")
      .select("id, label, kind, plan_id, sort_order")
      .eq("business_id", business.id)
      .eq("is_active", true)
      .in("kind", ["table", "booth"]),
  ]);

  const planName = new Map<string, string>();
  const planOrder = new Map<string, number>();
  for (const p of plans ?? []) {
    planName.set(p.id as string, (p.name as string) ?? "Floor");
    planOrder.set(p.id as string, (p.sort_order as number) ?? 0);
  }

  const base = process.env.NEXT_PUBLIC_SITE_URL || "https://www.surgetechpos.com";
  const businessName = (business as { name?: string }).name ?? "Menu";
  const guestOrderingOn = (business as { guest_ordering_enabled?: boolean }).guest_ordering_enabled === true;

  type Table = { id: string; label: string; planId: string; sort: number };
  const tables: Table[] = (elements ?? []).map((e) => ({
    id: e.id as string,
    label: (e.label as string) || "Table",
    planId: (e.plan_id as string) ?? "",
    sort: (e.sort_order as number) ?? 0,
  }));

  // Group by plan, ordered by plan then table.
  const planIds = Array.from(new Set(tables.map((t) => t.planId))).sort(
    (a, b) => (planOrder.get(a) ?? 0) - (planOrder.get(b) ?? 0)
  );
  const groups = planIds.map((pid) => ({
    id: pid,
    name: planName.get(pid) ?? "Floor",
    tables: tables
      .filter((t) => t.planId === pid)
      .sort((a, b) => a.sort - b.sort || a.label.localeCompare(b.label)),
  }));
  const showPlanHeadings = groups.length > 1;

  return (
    <div className="mx-auto max-w-5xl px-4 py-6">
      <style>{`
        @media print {
          body * { visibility: hidden; }
          #qr-print-area, #qr-print-area * { visibility: visible; }
          #qr-print-area { position: absolute; left: 0; top: 0; width: 100%; }
          .qr-placard { break-inside: avoid; }
        }
      `}</style>

      <div className="no-print mb-6 flex items-center justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold">Table QR codes</h1>
          <p className="text-sm text-muted-foreground mt-1">
            One code per table — guests scan to open their check and order. Print, cut, and place on each table.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Link href="/app/settings" className="shrink-0 text-sm rounded-md border border-border px-3 py-2 hover:bg-accent">
            Back to floor
          </Link>
          <PrintButton />
        </div>
      </div>

      {!guestOrderingOn && (
        <div className="no-print mb-6 rounded-md border border-amber-300 bg-amber-50 text-amber-900 px-4 py-3 text-sm">
          Guest ordering is currently <strong>off</strong>. You can still print these codes, but scanning won&apos;t work
          until you enable guest ordering in <Link href="/app/settings" className="underline">Settings → Floor</Link>.
        </div>
      )}

      {tables.length === 0 ? (
        <p className="text-sm text-muted-foreground">No tables on your floor plan yet. Add tables in Settings → Floor, then come back to print their codes.</p>
      ) : (
        <div id="qr-print-area">
          {groups.map((g) => (
            <section key={g.id} className="mb-8">
              {showPlanHeadings && <h2 className="text-sm font-semibold text-muted-foreground mb-3">{g.name}</h2>}
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
                {g.tables.map((t) => {
                  const url = `${base}/order/${business.id}/${t.id}`;
                  const svg = qrSvg(url, { ecc: "M", border: 2 });
                  return (
                    <div
                      key={t.id}
                      className="qr-placard rounded-xl border border-border bg-white text-zinc-900 p-4 flex flex-col items-center text-center"
                    >
                      <div className="text-lg font-bold">{t.label}</div>
                      <div className="text-xs text-zinc-500 mb-2">{businessName}</div>
                      <div
                        className="w-full max-w-[180px] aspect-square"
                        dangerouslySetInnerHTML={{ __html: svg }}
                      />
                      <div className="mt-2 text-xs font-medium text-zinc-700">Scan to order &amp; pay</div>
                    </div>
                  );
                })}
              </div>
            </section>
          ))}
        </div>
      )}
    </div>
  );
}
